import { QuestTemplate } from '@penguin/types';

export const QUEST_POOL: QuestTemplate[] = [
  {
    id: 'quest_pet',
    title: 'Vuốt Ve Yêu Thương',
    description: 'Vuốt ve các chú chim cánh cụt 5 lần.',
    icon: 'nurture',
    targetType: 'pet',
    targetCount: 5,
    rewardCoins: 50,
    rewardExp: 25,
  },
  {
    id: 'quest_feed',
    title: 'Bữa Ăn Ngon Miệng',
    description: 'Cho chim cánh cụt ăn thức ăn ngon 3 lần.',
    icon: 'feed',
    targetType: 'feed',
    targetCount: 3,
    rewardCoins: 60,
    rewardExp: 30,
  },
  {
    id: 'quest_hatch',
    title: 'Mầm Sống Mới',
    description: 'Ấp nở thành công 1 quả trứng trên đảo.',
    icon: 'hatch',
    targetType: 'hatch',
    targetCount: 1,
    rewardCoins: 100,
    rewardExp: 50,
    rewardGems: 1,
  },
  {
    id: 'quest_shop',
    title: 'Khách Hàng Thân Thiết',
    description: 'Mua 2 món hàng bất kỳ trong Cửa Hàng.',
    icon: 'shop',
    targetType: 'buy_shop',
    targetCount: 2,
    rewardCoins: 80,
    rewardExp: 35,
  },
  {
    id: 'quest_decorate',
    title: 'Kiến Trúc Sư Đảo Băng',
    description: 'Đặt hoặc thay đổi 1 đồ trang trí trên đảo.',
    icon: 'decorate',
    targetType: 'place_decoration',
    targetCount: 1,
    rewardCoins: 70,
    rewardExp: 40,
  },
];
